In [5]:
import pandas as pd

# 코드를 작성하세요.
df = pd.read_csv('data/mega_millions.csv', index_col=0)
# 정답 출력
df

           Winning Numbers  Mega Ball  Multiplier
Draw Date
02/15/2019  10 38 40 43 65         12         2.0
02/12/2019  15 32 39 50 65          7         3.0
02/08/2019  14 24 31 42 48         13         3.0
02/05/2019  03 34 36 59 66          7         2.0
02/01/2019  02 37 48 66 68         11         5.0
01/29/2019  10 33 53 54 62         22         2.0
01/25/2019  08 16 30 38 61         10         2.0
01/22/2019  04 15 37 59 64         16         5.0
01/18/2019  02 43 48 62 64         24         3.0
01/15/2019  29 52 58 60 62          7         2.0
01/11/2019  04 05 31 62 69         20         3.0
01/08/2019  13 26 29 38 64          5         5.0
01/04/2019  21 29 35 54 60         15         4.0
01/01/2019  34 44 57 62 70         14         4.0
12/28/2018  09 10 25 37 38         21         2.0
12/25/2018  02 08 42 43 50          6         3.0
12/21/2018  10 13 61 62 70          5         3.0
12/18/2018  13 22 32 60 69          9         3.0
12/14/2018  05 22 26 43 49         23         4.0
12/11/2018  04 38 39 54 59         12         2.0
12/07/2018  04 10 20 33 57         13         3.0
12/04/2018  28 31 41 42 50          4         3.0
11/30/2018  25 28 40 43 63         19         3.0
11/27/2018  12 24 37 42 57         18         4.0
11/23/2018  07 10 30 33 59         23         4.0
11/20/2018  10 16 31 42 66         10         3.0
11/16/2018  33 36 63 68 69         16         3.0
11/13/2018  34 46 57 65 69         11         3.0
11/09/2018  08 14 27 57 67          5         4.0
11/06/2018  28 34 37 56 69         12         2.0
...                    ...        ...         ...
08/27/2002  02 05 11 18 45         22         NaN
08/23/2002  05 19 20 45 48         44         NaN
08/20/2002  02 13 20 23 43          6         NaN
08/16/2002  22 31 33 44 52         43         NaN
08/13/2002  03 10 15 18 25         52         NaN
08/09/2002  07 17 23 43 44         26         NaN
08/06/2002  02 06 38 40 50         14         NaN
08/02/2002  10 16 23 28 31          7         NaN
07/30/2002  02 06 22 27 44          1         NaN
07/26/2002  20 27 28 37 49         32         NaN
07/23/2002  10 12 29 32 38          7         NaN
07/19/2002  07 15 24 37 46          9         NaN
07/16/2002  10 24 35 49 52         47         NaN
07/12/2002  13 19 23 38 47         15         NaN
07/09/2002  26 29 31 44 48         40         NaN
07/05/2002  11 20 26 29 41         41         NaN
07/02/2002  14 22 32 35 44          6         NaN
06/28/2002  18 31 49 50 51          4         NaN
06/25/2002  04 18 21 27 41         50         NaN
06/21/2002  13 18 32 39 49          6         NaN
06/18/2002  06 13 18 27 45         18         NaN
06/14/2002  04 08 32 37 43          2         NaN
06/11/2002  05 06 09 33 44         52         NaN
06/07/2002  14 22 27 28 42         13         NaN
06/04/2002  03 25 29 30 48         48         NaN
05/31/2002  12 28 45 46 52         47         NaN
05/28/2002  06 21 22 29 32         24         NaN
05/24/2002  02 04 32 44 52         36         NaN
05/21/2002  04 28 39 41 44          9         NaN
05/17/2002  15 18 25 33 47         30         NaN

[1746 rows x 3 columns]

In [6]:
import pandas as pd

df = pd.read_csv('data/mega_millions.csv', index_col='Draw Date')
df # 정답 출력

           Winning Numbers  Mega Ball  Multiplier
Draw Date
02/15/2019  10 38 40 43 65         12         2.0
02/12/2019  15 32 39 50 65          7         3.0
02/08/2019  14 24 31 42 48         13         3.0
02/05/2019  03 34 36 59 66          7         2.0
02/01/2019  02 37 48 66 68         11         5.0
01/29/2019  10 33 53 54 62         22         2.0
01/25/2019  08 16 30 38 61         10         2.0
01/22/2019  04 15 37 59 64         16         5.0
01/18/2019  02 43 48 62 64         24         3.0
01/15/2019  29 52 58 60 62          7         2.0
01/11/2019  04 05 31 62 69         20         3.0
01/08/2019  13 26 29 38 64          5         5.0
01/04/2019  21 29 35 54 60         15         4.0
01/01/2019  34 44 57 62 70         14         4.0
12/28/2018  09 10 25 37 38         21         2.0
12/25/2018  02 08 42 43 50          6         3.0
12/21/2018  10 13 61 62 70          5         3.0
12/18/2018  13 22 32 60 69          9         3.0
12/14/2018  05 22 26 43 49         23         4.0
12/11/2018  04 38 39 54 59         12         2.0
12/07/2018  04 10 20 33 57         13         3.0
12/04/2018  28 31 41 42 50          4         3.0
11/30/2018  25 28 40 43 63         19         3.0
11/27/2018  12 24 37 42 57         18         4.0
11/23/2018  07 10 30 33 59         23         4.0
11/20/2018  10 16 31 42 66         10         3.0
11/16/2018  33 36 63 68 69         16         3.0
11/13/2018  34 46 57 65 69         11         3.0
11/09/2018  08 14 27 57 67          5         4.0
11/06/2018  28 34 37 56 69         12         2.0
...                    ...        ...         ...
08/27/2002  02 05 11 18 45         22         NaN
08/23/2002  05 19 20 45 48         44         NaN
08/20/2002  02 13 20 23 43          6         NaN
08/16/2002  22 31 33 44 52         43         NaN
08/13/2002  03 10 15 18 25         52         NaN
08/09/2002  07 17 23 43 44         26         NaN
08/06/2002  02 06 38 40 50         14         NaN
08/02/2002  10 16 23 28 31          7         NaN
07/30/2002  02 06 22 27 44          1         NaN
07/26/2002  20 27 28 37 49         32         NaN
07/23/2002  10 12 29 32 38          7         NaN
07/19/2002  07 15 24 37 46          9         NaN
07/16/2002  10 24 35 49 52         47         NaN
07/12/2002  13 19 23 38 47         15         NaN
07/09/2002  26 29 31 44 48         40         NaN
07/05/2002  11 20 26 29 41         41         NaN
07/02/2002  14 22 32 35 44          6         NaN
06/28/2002  18 31 49 50 51          4         NaN
06/25/2002  04 18 21 27 41         50         NaN
06/21/2002  13 18 32 39 49          6         NaN
06/18/2002  06 13 18 27 45         18         NaN
06/14/2002  04 08 32 37 43          2         NaN
06/11/2002  05 06 09 33 44         52         NaN
06/07/2002  14 22 27 28 42         13         NaN
06/04/2002  03 25 29 30 48         48         NaN
05/31/2002  12 28 45 46 52         47         NaN
05/28/2002  06 21 22 29 32         24         NaN
05/24/2002  02 04 32 44 52         36         NaN
05/21/2002  04 28 39 41 44          9         NaN
05/17/2002  15 18 25 33 47         30         NaN

[1746 rows x 3 columns]